version: 2

jobs:
  lint:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --require-hashes -r requirements/requirements.txt
      - run:
          name: Run lint
          command: make docs-lint

workflows:
  version: 2
  build:
    jobs:
      - lint
