---
name: CI

on:
  push:
    branches: ["main"]

  pull_request:
    types: ["opened", "synchronize"]

  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    # We use a standard Debian image to mirror a typical developer environment.
    # This should be updated whenever a new Debian stable version is available.
    container: debian:trixie
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends make python3-poetry
          poetry install --no-ansi
      - name: Run lint
        run: |
          make docs-lint

  build:
    name: Build
    uses: freedomofpress/actionslib/.github/workflows/oci-build.yaml@main
    permissions:
      contents: read
      actions: read
    with:
      context: "."
      containerfile: deploy/Dockerfile
      build-args: |
        GIT_BRANCH=${{ github.ref_name }}
